# =====================================================================
# Smcsrind Extension Verification Test
# =====================================================================

TARGET = smcsrind_test.elf

SPIKE_ISA_EXT = _smcsrind_sscsrind_smstateen

EXT_OBJS = \
    main.o \
    tests/test_register.o

include ../common/Makefile.common
