/*
 * Copyright (c) 2026 Alibaba Group.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "types.h"
#include "encoding.h"

/* ===================================================================
 * Dynamic CSR read/write
 *
 * RISC-V CSR instructions require compile-time immediate operands.
 * These functions use switch-case to map runtime CSR addresses to
 * compile-time CSR access instructions.
 *
 * CSR address macros are defined in sm_defs.h, ss_defs.h, and hyp_defs.h
 * (all included via encoding.h). Only macro names
 * (not raw hex values) are used in switch cases for maintainability.
 * =================================================================== */

/* Helper macros for generating switch cases.
 * Uses CSR_STR (two-level stringify) so that macro arguments like
 * CSR_PMPCFG0 are expanded to 0x3A0 before stringification,
 * producing "0x3A0" for the assembler. */
#define _CSR_READ_CASE(addr) \
    case (addr): asm volatile("csrr %0, " CSR_STR(addr) : "=r"(val) :: "memory"); break;

#define _CSR_WRITE_CASE(addr) \
    case (addr): asm volatile("csrw " CSR_STR(addr) ", %0" :: "r"(val) : "memory"); break;

/* ===================================================================
 * csr_read - read a CSR by runtime address
 * =================================================================== */
uintptr_t csr_read(uint16_t csr) {
    uintptr_t val = 0;

    switch (csr) {
    /* ----- pmpcfg registers ----- */
    _CSR_READ_CASE(CSR_PMPCFG0)
    _CSR_READ_CASE(CSR_PMPCFG1)
    _CSR_READ_CASE(CSR_PMPCFG2)
    _CSR_READ_CASE(CSR_PMPCFG3)
    _CSR_READ_CASE(CSR_PMPCFG4)
    _CSR_READ_CASE(CSR_PMPCFG5)
    _CSR_READ_CASE(CSR_PMPCFG6)
    _CSR_READ_CASE(CSR_PMPCFG7)
    _CSR_READ_CASE(CSR_PMPCFG8)
    _CSR_READ_CASE(CSR_PMPCFG9)
    _CSR_READ_CASE(CSR_PMPCFG10)
    _CSR_READ_CASE(CSR_PMPCFG11)
    _CSR_READ_CASE(CSR_PMPCFG12)
    _CSR_READ_CASE(CSR_PMPCFG13)
    _CSR_READ_CASE(CSR_PMPCFG14)
    _CSR_READ_CASE(CSR_PMPCFG15)

    /* ----- pmpaddr registers ----- */
    _CSR_READ_CASE(CSR_PMPADDR0)
    _CSR_READ_CASE(CSR_PMPADDR1)
    _CSR_READ_CASE(CSR_PMPADDR2)
    _CSR_READ_CASE(CSR_PMPADDR3)
    _CSR_READ_CASE(CSR_PMPADDR4)
    _CSR_READ_CASE(CSR_PMPADDR5)
    _CSR_READ_CASE(CSR_PMPADDR6)
    _CSR_READ_CASE(CSR_PMPADDR7)
    _CSR_READ_CASE(CSR_PMPADDR8)
    _CSR_READ_CASE(CSR_PMPADDR9)
    _CSR_READ_CASE(CSR_PMPADDR10)
    _CSR_READ_CASE(CSR_PMPADDR11)
    _CSR_READ_CASE(CSR_PMPADDR12)
    _CSR_READ_CASE(CSR_PMPADDR13)
    _CSR_READ_CASE(CSR_PMPADDR14)
    _CSR_READ_CASE(CSR_PMPADDR15)
    _CSR_READ_CASE(CSR_PMPADDR16)
    _CSR_READ_CASE(CSR_PMPADDR17)
    _CSR_READ_CASE(CSR_PMPADDR18)
    _CSR_READ_CASE(CSR_PMPADDR19)
    _CSR_READ_CASE(CSR_PMPADDR20)
    _CSR_READ_CASE(CSR_PMPADDR21)
    _CSR_READ_CASE(CSR_PMPADDR22)
    _CSR_READ_CASE(CSR_PMPADDR23)
    _CSR_READ_CASE(CSR_PMPADDR24)
    _CSR_READ_CASE(CSR_PMPADDR25)
    _CSR_READ_CASE(CSR_PMPADDR26)
    _CSR_READ_CASE(CSR_PMPADDR27)
    _CSR_READ_CASE(CSR_PMPADDR28)
    _CSR_READ_CASE(CSR_PMPADDR29)
    _CSR_READ_CASE(CSR_PMPADDR30)
    _CSR_READ_CASE(CSR_PMPADDR31)
    _CSR_READ_CASE(CSR_PMPADDR32)
    _CSR_READ_CASE(CSR_PMPADDR33)
    _CSR_READ_CASE(CSR_PMPADDR34)
    _CSR_READ_CASE(CSR_PMPADDR35)
    _CSR_READ_CASE(CSR_PMPADDR36)
    _CSR_READ_CASE(CSR_PMPADDR37)
    _CSR_READ_CASE(CSR_PMPADDR38)
    _CSR_READ_CASE(CSR_PMPADDR39)
    _CSR_READ_CASE(CSR_PMPADDR40)
    _CSR_READ_CASE(CSR_PMPADDR41)
    _CSR_READ_CASE(CSR_PMPADDR42)
    _CSR_READ_CASE(CSR_PMPADDR43)
    _CSR_READ_CASE(CSR_PMPADDR44)
    _CSR_READ_CASE(CSR_PMPADDR45)
    _CSR_READ_CASE(CSR_PMPADDR46)
    _CSR_READ_CASE(CSR_PMPADDR47)
    _CSR_READ_CASE(CSR_PMPADDR48)
    _CSR_READ_CASE(CSR_PMPADDR49)
    _CSR_READ_CASE(CSR_PMPADDR50)
    _CSR_READ_CASE(CSR_PMPADDR51)
    _CSR_READ_CASE(CSR_PMPADDR52)
    _CSR_READ_CASE(CSR_PMPADDR53)
    _CSR_READ_CASE(CSR_PMPADDR54)
    _CSR_READ_CASE(CSR_PMPADDR55)
    _CSR_READ_CASE(CSR_PMPADDR56)
    _CSR_READ_CASE(CSR_PMPADDR57)
    _CSR_READ_CASE(CSR_PMPADDR58)
    _CSR_READ_CASE(CSR_PMPADDR59)
    _CSR_READ_CASE(CSR_PMPADDR60)
    _CSR_READ_CASE(CSR_PMPADDR61)
    _CSR_READ_CASE(CSR_PMPADDR62)
    _CSR_READ_CASE(CSR_PMPADDR63)

    /* ----- mseccfg ----- */
    _CSR_READ_CASE(CSR_MSECCFG)
#if __riscv_xlen == 32
    _CSR_READ_CASE(CSR_MSECCFGH)
#endif

    /* ----- Common CSRs (for privilege switching etc.) ----- */
    _CSR_READ_CASE(CSR_MSTATUS)
    _CSR_READ_CASE(CSR_MISA)
    _CSR_READ_CASE(CSR_MEDELEG)
    _CSR_READ_CASE(CSR_MIDELEG)
    _CSR_READ_CASE(CSR_MIE)
    _CSR_READ_CASE(CSR_MTVEC)
    _CSR_READ_CASE(CSR_MSCRATCH)
    _CSR_READ_CASE(CSR_MEPC)
    _CSR_READ_CASE(CSR_MCAUSE)
    _CSR_READ_CASE(CSR_MTVAL)
    _CSR_READ_CASE(CSR_MIP)
    _CSR_READ_CASE(CSR_SSTATUS)
    _CSR_READ_CASE(CSR_SIE)
    _CSR_READ_CASE(CSR_STVEC)
    _CSR_READ_CASE(CSR_SSCRATCH)
    _CSR_READ_CASE(CSR_SEPC)
    _CSR_READ_CASE(CSR_SCAUSE)
    _CSR_READ_CASE(CSR_STVAL)
    _CSR_READ_CASE(CSR_SIP)
    _CSR_READ_CASE(CSR_SATP)
    _CSR_READ_CASE(CSR_SENVCFG)
    _CSR_READ_CASE(CSR_MENVCFG)

    /* ----- Sstc extension CSRs ----- */
    _CSR_READ_CASE(CSR_STIMECMP)
    _CSR_READ_CASE(CSR_VSTIMECMP)

    /* ----- Counter configuration CSRs ----- */
    _CSR_READ_CASE(CSR_SCOUNTEREN)
    _CSR_READ_CASE(CSR_MCOUNTEREN)
    _CSR_READ_CASE(CSR_MCOUNTINHIBIT)

    /* ----- mhpmevent registers ----- */
    _CSR_READ_CASE(CSR_MHPMEVENT3)  _CSR_READ_CASE(CSR_MHPMEVENT4)  _CSR_READ_CASE(CSR_MHPMEVENT5)
    _CSR_READ_CASE(CSR_MHPMEVENT6)  _CSR_READ_CASE(CSR_MHPMEVENT7)  _CSR_READ_CASE(CSR_MHPMEVENT8)
    _CSR_READ_CASE(CSR_MHPMEVENT9)  _CSR_READ_CASE(CSR_MHPMEVENT10) _CSR_READ_CASE(CSR_MHPMEVENT11)
    _CSR_READ_CASE(CSR_MHPMEVENT12) _CSR_READ_CASE(CSR_MHPMEVENT13) _CSR_READ_CASE(CSR_MHPMEVENT14)
    _CSR_READ_CASE(CSR_MHPMEVENT15) _CSR_READ_CASE(CSR_MHPMEVENT16) _CSR_READ_CASE(CSR_MHPMEVENT17)
    _CSR_READ_CASE(CSR_MHPMEVENT18) _CSR_READ_CASE(CSR_MHPMEVENT19) _CSR_READ_CASE(CSR_MHPMEVENT20)
    _CSR_READ_CASE(CSR_MHPMEVENT21) _CSR_READ_CASE(CSR_MHPMEVENT22) _CSR_READ_CASE(CSR_MHPMEVENT23)
    _CSR_READ_CASE(CSR_MHPMEVENT24) _CSR_READ_CASE(CSR_MHPMEVENT25) _CSR_READ_CASE(CSR_MHPMEVENT26)
    _CSR_READ_CASE(CSR_MHPMEVENT27) _CSR_READ_CASE(CSR_MHPMEVENT28) _CSR_READ_CASE(CSR_MHPMEVENT29)
    _CSR_READ_CASE(CSR_MHPMEVENT30) _CSR_READ_CASE(CSR_MHPMEVENT31)

    /* ----- mcycle / minstret ----- */
    _CSR_READ_CASE(CSR_MCYCLE)
    _CSR_READ_CASE(CSR_MINSTRET)

    /* ----- mhpmcounter registers ----- */
    _CSR_READ_CASE(CSR_MHPMCOUNTER3)  _CSR_READ_CASE(CSR_MHPMCOUNTER4)  _CSR_READ_CASE(CSR_MHPMCOUNTER5)
    _CSR_READ_CASE(CSR_MHPMCOUNTER6)  _CSR_READ_CASE(CSR_MHPMCOUNTER7)  _CSR_READ_CASE(CSR_MHPMCOUNTER8)
    _CSR_READ_CASE(CSR_MHPMCOUNTER9)  _CSR_READ_CASE(CSR_MHPMCOUNTER10) _CSR_READ_CASE(CSR_MHPMCOUNTER11)
    _CSR_READ_CASE(CSR_MHPMCOUNTER12) _CSR_READ_CASE(CSR_MHPMCOUNTER13) _CSR_READ_CASE(CSR_MHPMCOUNTER14)
    _CSR_READ_CASE(CSR_MHPMCOUNTER15) _CSR_READ_CASE(CSR_MHPMCOUNTER16) _CSR_READ_CASE(CSR_MHPMCOUNTER17)
    _CSR_READ_CASE(CSR_MHPMCOUNTER18) _CSR_READ_CASE(CSR_MHPMCOUNTER19) _CSR_READ_CASE(CSR_MHPMCOUNTER20)
    _CSR_READ_CASE(CSR_MHPMCOUNTER21) _CSR_READ_CASE(CSR_MHPMCOUNTER22) _CSR_READ_CASE(CSR_MHPMCOUNTER23)
    _CSR_READ_CASE(CSR_MHPMCOUNTER24) _CSR_READ_CASE(CSR_MHPMCOUNTER25) _CSR_READ_CASE(CSR_MHPMCOUNTER26)
    _CSR_READ_CASE(CSR_MHPMCOUNTER27) _CSR_READ_CASE(CSR_MHPMCOUNTER28) _CSR_READ_CASE(CSR_MHPMCOUNTER29)
    _CSR_READ_CASE(CSR_MHPMCOUNTER30) _CSR_READ_CASE(CSR_MHPMCOUNTER31)

#if __riscv_xlen == 32
    /* ----- RV32 high-half base counters ----- */
    _CSR_READ_CASE(CSR_MCYCLEH)
    _CSR_READ_CASE(CSR_MINSTRETH)

    /* ----- RV32 high-half mhpmcounter registers ----- */
    _CSR_READ_CASE(CSR_MHPMCOUNTERH3)  _CSR_READ_CASE(CSR_MHPMCOUNTERH4)  _CSR_READ_CASE(CSR_MHPMCOUNTERH5)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH6)  _CSR_READ_CASE(CSR_MHPMCOUNTERH7)  _CSR_READ_CASE(CSR_MHPMCOUNTERH8)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH9)  _CSR_READ_CASE(CSR_MHPMCOUNTERH10) _CSR_READ_CASE(CSR_MHPMCOUNTERH11)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH12) _CSR_READ_CASE(CSR_MHPMCOUNTERH13) _CSR_READ_CASE(CSR_MHPMCOUNTERH14)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH15) _CSR_READ_CASE(CSR_MHPMCOUNTERH16) _CSR_READ_CASE(CSR_MHPMCOUNTERH17)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH18) _CSR_READ_CASE(CSR_MHPMCOUNTERH19) _CSR_READ_CASE(CSR_MHPMCOUNTERH20)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH21) _CSR_READ_CASE(CSR_MHPMCOUNTERH22) _CSR_READ_CASE(CSR_MHPMCOUNTERH23)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH24) _CSR_READ_CASE(CSR_MHPMCOUNTERH25) _CSR_READ_CASE(CSR_MHPMCOUNTERH26)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH27) _CSR_READ_CASE(CSR_MHPMCOUNTERH28) _CSR_READ_CASE(CSR_MHPMCOUNTERH29)
    _CSR_READ_CASE(CSR_MHPMCOUNTERH30) _CSR_READ_CASE(CSR_MHPMCOUNTERH31)
#endif

    /* ----- cycle / time / instret (read-only) ----- */
    _CSR_READ_CASE(CSR_CYCLE)
    _CSR_READ_CASE(CSR_TIME)
    _CSR_READ_CASE(CSR_INSTRET)

    /* ----- hpmcounter registers (read-only shadow) ----- */
    _CSR_READ_CASE(CSR_HPMCOUNTER3)  _CSR_READ_CASE(CSR_HPMCOUNTER4)  _CSR_READ_CASE(CSR_HPMCOUNTER5)
    _CSR_READ_CASE(CSR_HPMCOUNTER6)  _CSR_READ_CASE(CSR_HPMCOUNTER7)  _CSR_READ_CASE(CSR_HPMCOUNTER8)
    _CSR_READ_CASE(CSR_HPMCOUNTER9)  _CSR_READ_CASE(CSR_HPMCOUNTER10) _CSR_READ_CASE(CSR_HPMCOUNTER11)
    _CSR_READ_CASE(CSR_HPMCOUNTER12) _CSR_READ_CASE(CSR_HPMCOUNTER13) _CSR_READ_CASE(CSR_HPMCOUNTER14)
    _CSR_READ_CASE(CSR_HPMCOUNTER15) _CSR_READ_CASE(CSR_HPMCOUNTER16) _CSR_READ_CASE(CSR_HPMCOUNTER17)
    _CSR_READ_CASE(CSR_HPMCOUNTER18) _CSR_READ_CASE(CSR_HPMCOUNTER19) _CSR_READ_CASE(CSR_HPMCOUNTER20)
    _CSR_READ_CASE(CSR_HPMCOUNTER21) _CSR_READ_CASE(CSR_HPMCOUNTER22) _CSR_READ_CASE(CSR_HPMCOUNTER23)
    _CSR_READ_CASE(CSR_HPMCOUNTER24) _CSR_READ_CASE(CSR_HPMCOUNTER25) _CSR_READ_CASE(CSR_HPMCOUNTER26)
    _CSR_READ_CASE(CSR_HPMCOUNTER27) _CSR_READ_CASE(CSR_HPMCOUNTER28) _CSR_READ_CASE(CSR_HPMCOUNTER29)
    _CSR_READ_CASE(CSR_HPMCOUNTER30) _CSR_READ_CASE(CSR_HPMCOUNTER31)

    /* ----- scountovf (read-only) ----- */
    _CSR_READ_CASE(CSR_SCOUNTOVF)

#ifdef ENABLE_HYP
    /* ----- Hypervisor CSRs (HS-level) ----- */
    _CSR_READ_CASE(CSR_HSTATUS)
    _CSR_READ_CASE(CSR_HEDELEG)
    _CSR_READ_CASE(CSR_HIDELEG)
    _CSR_READ_CASE(CSR_HIE)
    _CSR_READ_CASE(CSR_HTIMEDELTA)
    _CSR_READ_CASE(CSR_HCOUNTEREN)
    _CSR_READ_CASE(CSR_HGEIE)
    _CSR_READ_CASE(CSR_HENVCFG)
    _CSR_READ_CASE(CSR_HTVAL)
    _CSR_READ_CASE(CSR_HIP)
    _CSR_READ_CASE(CSR_HVIP)
    _CSR_READ_CASE(CSR_HTINST)
    _CSR_READ_CASE(CSR_HGATP)
    _CSR_READ_CASE(CSR_HGEIP)

    /* ----- VS-level CSRs ----- */
    _CSR_READ_CASE(CSR_VSSTATUS)
    _CSR_READ_CASE(CSR_VSIE)
    _CSR_READ_CASE(CSR_VSTVEC)
    _CSR_READ_CASE(CSR_VSSCRATCH)
    _CSR_READ_CASE(CSR_VSEPC)
    _CSR_READ_CASE(CSR_VSCAUSE)
    _CSR_READ_CASE(CSR_VSTVAL)
    _CSR_READ_CASE(CSR_VSIP)
    _CSR_READ_CASE(CSR_VSATP)

    /* ----- M-mode hypervisor extension ----- */
    _CSR_READ_CASE(CSR_MTINST)
    _CSR_READ_CASE(CSR_MTVAL2)
#endif /* ENABLE_HYP */

    default:
        break;
    }

    return val;
}

/* ===================================================================
 * csr_write - write a CSR by runtime address
 * =================================================================== */
void csr_write(uint16_t csr, uintptr_t val) {
    switch (csr) {
    /* ----- pmpcfg registers ----- */
    _CSR_WRITE_CASE(CSR_PMPCFG0)
    _CSR_WRITE_CASE(CSR_PMPCFG1)
    _CSR_WRITE_CASE(CSR_PMPCFG2)
    _CSR_WRITE_CASE(CSR_PMPCFG3)
    _CSR_WRITE_CASE(CSR_PMPCFG4)
    _CSR_WRITE_CASE(CSR_PMPCFG5)
    _CSR_WRITE_CASE(CSR_PMPCFG6)
    _CSR_WRITE_CASE(CSR_PMPCFG7)
    _CSR_WRITE_CASE(CSR_PMPCFG8)
    _CSR_WRITE_CASE(CSR_PMPCFG9)
    _CSR_WRITE_CASE(CSR_PMPCFG10)
    _CSR_WRITE_CASE(CSR_PMPCFG11)
    _CSR_WRITE_CASE(CSR_PMPCFG12)
    _CSR_WRITE_CASE(CSR_PMPCFG13)
    _CSR_WRITE_CASE(CSR_PMPCFG14)
    _CSR_WRITE_CASE(CSR_PMPCFG15)

    /* ----- pmpaddr registers ----- */
    _CSR_WRITE_CASE(CSR_PMPADDR0)
    _CSR_WRITE_CASE(CSR_PMPADDR1)
    _CSR_WRITE_CASE(CSR_PMPADDR2)
    _CSR_WRITE_CASE(CSR_PMPADDR3)
    _CSR_WRITE_CASE(CSR_PMPADDR4)
    _CSR_WRITE_CASE(CSR_PMPADDR5)
    _CSR_WRITE_CASE(CSR_PMPADDR6)
    _CSR_WRITE_CASE(CSR_PMPADDR7)
    _CSR_WRITE_CASE(CSR_PMPADDR8)
    _CSR_WRITE_CASE(CSR_PMPADDR9)
    _CSR_WRITE_CASE(CSR_PMPADDR10)
    _CSR_WRITE_CASE(CSR_PMPADDR11)
    _CSR_WRITE_CASE(CSR_PMPADDR12)
    _CSR_WRITE_CASE(CSR_PMPADDR13)
    _CSR_WRITE_CASE(CSR_PMPADDR14)
    _CSR_WRITE_CASE(CSR_PMPADDR15)
    _CSR_WRITE_CASE(CSR_PMPADDR16)
    _CSR_WRITE_CASE(CSR_PMPADDR17)
    _CSR_WRITE_CASE(CSR_PMPADDR18)
    _CSR_WRITE_CASE(CSR_PMPADDR19)
    _CSR_WRITE_CASE(CSR_PMPADDR20)
    _CSR_WRITE_CASE(CSR_PMPADDR21)
    _CSR_WRITE_CASE(CSR_PMPADDR22)
    _CSR_WRITE_CASE(CSR_PMPADDR23)
    _CSR_WRITE_CASE(CSR_PMPADDR24)
    _CSR_WRITE_CASE(CSR_PMPADDR25)
    _CSR_WRITE_CASE(CSR_PMPADDR26)
    _CSR_WRITE_CASE(CSR_PMPADDR27)
    _CSR_WRITE_CASE(CSR_PMPADDR28)
    _CSR_WRITE_CASE(CSR_PMPADDR29)
    _CSR_WRITE_CASE(CSR_PMPADDR30)
    _CSR_WRITE_CASE(CSR_PMPADDR31)
    _CSR_WRITE_CASE(CSR_PMPADDR32)
    _CSR_WRITE_CASE(CSR_PMPADDR33)
    _CSR_WRITE_CASE(CSR_PMPADDR34)
    _CSR_WRITE_CASE(CSR_PMPADDR35)
    _CSR_WRITE_CASE(CSR_PMPADDR36)
    _CSR_WRITE_CASE(CSR_PMPADDR37)
    _CSR_WRITE_CASE(CSR_PMPADDR38)
    _CSR_WRITE_CASE(CSR_PMPADDR39)
    _CSR_WRITE_CASE(CSR_PMPADDR40)
    _CSR_WRITE_CASE(CSR_PMPADDR41)
    _CSR_WRITE_CASE(CSR_PMPADDR42)
    _CSR_WRITE_CASE(CSR_PMPADDR43)
    _CSR_WRITE_CASE(CSR_PMPADDR44)
    _CSR_WRITE_CASE(CSR_PMPADDR45)
    _CSR_WRITE_CASE(CSR_PMPADDR46)
    _CSR_WRITE_CASE(CSR_PMPADDR47)
    _CSR_WRITE_CASE(CSR_PMPADDR48)
    _CSR_WRITE_CASE(CSR_PMPADDR49)
    _CSR_WRITE_CASE(CSR_PMPADDR50)
    _CSR_WRITE_CASE(CSR_PMPADDR51)
    _CSR_WRITE_CASE(CSR_PMPADDR52)
    _CSR_WRITE_CASE(CSR_PMPADDR53)
    _CSR_WRITE_CASE(CSR_PMPADDR54)
    _CSR_WRITE_CASE(CSR_PMPADDR55)
    _CSR_WRITE_CASE(CSR_PMPADDR56)
    _CSR_WRITE_CASE(CSR_PMPADDR57)
    _CSR_WRITE_CASE(CSR_PMPADDR58)
    _CSR_WRITE_CASE(CSR_PMPADDR59)
    _CSR_WRITE_CASE(CSR_PMPADDR60)
    _CSR_WRITE_CASE(CSR_PMPADDR61)
    _CSR_WRITE_CASE(CSR_PMPADDR62)
    _CSR_WRITE_CASE(CSR_PMPADDR63)

    /* ----- mseccfg ----- */
    _CSR_WRITE_CASE(CSR_MSECCFG)
#if __riscv_xlen == 32
    _CSR_WRITE_CASE(CSR_MSECCFGH)
#endif

    /* ----- Common CSRs ----- */
    _CSR_WRITE_CASE(CSR_MSTATUS)
    _CSR_WRITE_CASE(CSR_MISA)
    _CSR_WRITE_CASE(CSR_MEDELEG)
    _CSR_WRITE_CASE(CSR_MIDELEG)
    _CSR_WRITE_CASE(CSR_MIE)
    _CSR_WRITE_CASE(CSR_MTVEC)
    _CSR_WRITE_CASE(CSR_MSCRATCH)
    _CSR_WRITE_CASE(CSR_MEPC)
    _CSR_WRITE_CASE(CSR_MCAUSE)
    _CSR_WRITE_CASE(CSR_MTVAL)
    _CSR_WRITE_CASE(CSR_MIP)
    _CSR_WRITE_CASE(CSR_SSTATUS)
    _CSR_WRITE_CASE(CSR_SIE)
    _CSR_WRITE_CASE(CSR_STVEC)
    _CSR_WRITE_CASE(CSR_SSCRATCH)
    _CSR_WRITE_CASE(CSR_SEPC)
    _CSR_WRITE_CASE(CSR_SCAUSE)
    _CSR_WRITE_CASE(CSR_STVAL)
    _CSR_WRITE_CASE(CSR_SIP)
    _CSR_WRITE_CASE(CSR_SATP)
    _CSR_WRITE_CASE(CSR_SENVCFG)
    _CSR_WRITE_CASE(CSR_MENVCFG)

    /* ----- Sstc extension CSRs ----- */
    _CSR_WRITE_CASE(CSR_STIMECMP)
    _CSR_WRITE_CASE(CSR_VSTIMECMP)

    /* ----- Counter configuration CSRs ----- */
    _CSR_WRITE_CASE(CSR_SCOUNTEREN)
    _CSR_WRITE_CASE(CSR_MCOUNTEREN)
    _CSR_WRITE_CASE(CSR_MCOUNTINHIBIT)

    /* ----- mhpmevent registers ----- */
    _CSR_WRITE_CASE(CSR_MHPMEVENT3)  _CSR_WRITE_CASE(CSR_MHPMEVENT4)  _CSR_WRITE_CASE(CSR_MHPMEVENT5)
    _CSR_WRITE_CASE(CSR_MHPMEVENT6)  _CSR_WRITE_CASE(CSR_MHPMEVENT7)  _CSR_WRITE_CASE(CSR_MHPMEVENT8)
    _CSR_WRITE_CASE(CSR_MHPMEVENT9)  _CSR_WRITE_CASE(CSR_MHPMEVENT10) _CSR_WRITE_CASE(CSR_MHPMEVENT11)
    _CSR_WRITE_CASE(CSR_MHPMEVENT12) _CSR_WRITE_CASE(CSR_MHPMEVENT13) _CSR_WRITE_CASE(CSR_MHPMEVENT14)
    _CSR_WRITE_CASE(CSR_MHPMEVENT15) _CSR_WRITE_CASE(CSR_MHPMEVENT16) _CSR_WRITE_CASE(CSR_MHPMEVENT17)
    _CSR_WRITE_CASE(CSR_MHPMEVENT18) _CSR_WRITE_CASE(CSR_MHPMEVENT19) _CSR_WRITE_CASE(CSR_MHPMEVENT20)
    _CSR_WRITE_CASE(CSR_MHPMEVENT21) _CSR_WRITE_CASE(CSR_MHPMEVENT22) _CSR_WRITE_CASE(CSR_MHPMEVENT23)
    _CSR_WRITE_CASE(CSR_MHPMEVENT24) _CSR_WRITE_CASE(CSR_MHPMEVENT25) _CSR_WRITE_CASE(CSR_MHPMEVENT26)
    _CSR_WRITE_CASE(CSR_MHPMEVENT27) _CSR_WRITE_CASE(CSR_MHPMEVENT28) _CSR_WRITE_CASE(CSR_MHPMEVENT29)
    _CSR_WRITE_CASE(CSR_MHPMEVENT30) _CSR_WRITE_CASE(CSR_MHPMEVENT31)

    /* ----- mcycle / minstret ----- */
    _CSR_WRITE_CASE(CSR_MCYCLE)
    _CSR_WRITE_CASE(CSR_MINSTRET)

    /* ----- mhpmcounter registers ----- */
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER3)  _CSR_WRITE_CASE(CSR_MHPMCOUNTER4)  _CSR_WRITE_CASE(CSR_MHPMCOUNTER5)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER6)  _CSR_WRITE_CASE(CSR_MHPMCOUNTER7)  _CSR_WRITE_CASE(CSR_MHPMCOUNTER8)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER9)  _CSR_WRITE_CASE(CSR_MHPMCOUNTER10) _CSR_WRITE_CASE(CSR_MHPMCOUNTER11)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER12) _CSR_WRITE_CASE(CSR_MHPMCOUNTER13) _CSR_WRITE_CASE(CSR_MHPMCOUNTER14)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER15) _CSR_WRITE_CASE(CSR_MHPMCOUNTER16) _CSR_WRITE_CASE(CSR_MHPMCOUNTER17)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER18) _CSR_WRITE_CASE(CSR_MHPMCOUNTER19) _CSR_WRITE_CASE(CSR_MHPMCOUNTER20)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER21) _CSR_WRITE_CASE(CSR_MHPMCOUNTER22) _CSR_WRITE_CASE(CSR_MHPMCOUNTER23)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER24) _CSR_WRITE_CASE(CSR_MHPMCOUNTER25) _CSR_WRITE_CASE(CSR_MHPMCOUNTER26)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER27) _CSR_WRITE_CASE(CSR_MHPMCOUNTER28) _CSR_WRITE_CASE(CSR_MHPMCOUNTER29)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTER30) _CSR_WRITE_CASE(CSR_MHPMCOUNTER31)

#if __riscv_xlen == 32
    /* ----- RV32 high-half base counters ----- */
    _CSR_WRITE_CASE(CSR_MCYCLEH)
    _CSR_WRITE_CASE(CSR_MINSTRETH)

    /* ----- RV32 high-half mhpmcounter registers ----- */
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH3)  _CSR_WRITE_CASE(CSR_MHPMCOUNTERH4)  _CSR_WRITE_CASE(CSR_MHPMCOUNTERH5)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH6)  _CSR_WRITE_CASE(CSR_MHPMCOUNTERH7)  _CSR_WRITE_CASE(CSR_MHPMCOUNTERH8)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH9)  _CSR_WRITE_CASE(CSR_MHPMCOUNTERH10) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH11)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH12) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH13) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH14)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH15) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH16) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH17)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH18) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH19) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH20)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH21) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH22) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH23)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH24) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH25) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH26)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH27) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH28) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH29)
    _CSR_WRITE_CASE(CSR_MHPMCOUNTERH30) _CSR_WRITE_CASE(CSR_MHPMCOUNTERH31)
#endif

#ifdef ENABLE_HYP
    /* ----- Hypervisor CSRs (HS-level) ----- */
    _CSR_WRITE_CASE(CSR_HSTATUS)
    _CSR_WRITE_CASE(CSR_HEDELEG)
    _CSR_WRITE_CASE(CSR_HIDELEG)
    _CSR_WRITE_CASE(CSR_HIE)
    _CSR_WRITE_CASE(CSR_HTIMEDELTA)
    _CSR_WRITE_CASE(CSR_HCOUNTEREN)
    _CSR_WRITE_CASE(CSR_HGEIE)
    _CSR_WRITE_CASE(CSR_HENVCFG)
    _CSR_WRITE_CASE(CSR_HTVAL)
    _CSR_WRITE_CASE(CSR_HIP)
    _CSR_WRITE_CASE(CSR_HVIP)
    _CSR_WRITE_CASE(CSR_HTINST)
    _CSR_WRITE_CASE(CSR_HGATP)

    /* ----- VS-level CSRs ----- */
    _CSR_WRITE_CASE(CSR_VSSTATUS)
    _CSR_WRITE_CASE(CSR_VSIE)
    _CSR_WRITE_CASE(CSR_VSTVEC)
    _CSR_WRITE_CASE(CSR_VSSCRATCH)
    _CSR_WRITE_CASE(CSR_VSEPC)
    _CSR_WRITE_CASE(CSR_VSCAUSE)
    _CSR_WRITE_CASE(CSR_VSTVAL)
    _CSR_WRITE_CASE(CSR_VSIP)
    _CSR_WRITE_CASE(CSR_VSATP)

    /* ----- M-mode hypervisor extension ----- */
    _CSR_WRITE_CASE(CSR_MTINST)
    _CSR_WRITE_CASE(CSR_MTVAL2)
#endif /* ENABLE_HYP */

    default:
        break;
    }
}
