# =====================================================================
# Sscsrind Extension Verification Test
# =====================================================================

TARGET = sscsrind_test.elf

SPIKE_ISA_EXT = _sscsrind_smstateen

EXT_OBJS = \
    main.o \
    tests/test_register.o

ENABLE_VM  = 1

include ../common/Makefile.common
